### ISSUE TITLE
Add Python 3 compatibility

### ISSUE THREAD

**Issue by cgoldberg** [edx/bok-choy#137]
Are there any plans for updating bok-choy to be Python 3 compatible?

Python 3 is finally seeing major adoption... and I think the following Python versions should be targeted: 2.7, 3.3, 3.4, 3.5

Rather than creating a Python3 fork and maintaining 2 code bases, this would be best done by using a single code base that runs under Python 2 or Python 3.  (perhaps using `six` as a compatibility helper).

If there are no plans for this on the horizon, would a PR contributing Python3 support be considered for merging? (I might have spare cycles to take this on)

**Comment by jzoldak** [comment]
Hey @cgoldberg.
We haven't yet encountered the need to run under Python 3 so it's not on our roadmap.
I would be totally psyched to review and merge a PR adding it, that'd be awesome if you have the cycles.
Agreed on the single codebase.

**Comment by jzoldak** [comment]
@cgoldberg I'm putting together and prioritizing a list of bok-choy new features, improvements, and cleanup. 
This is definitely on the list. As it looks now, it seems like the community is skipping 3.3 and 3.4, in favor of leaping directly to 3.5. Would that work for your purposes?

**Comment by cgoldberg** [comment]
yea.. 3.5 is great for me.

**Comment by ajpal** [comment]
Addressed by #168
