### ISSUE TITLE
Update FirefoxDriver usage to GeckoDriver/Marionette

### ISSUE THREAD

**Issue by cgoldberg** [edx/bok-choy#154]
‼️ just a friendly PSA:

The existing FirefoxDriver in selenium is deprecated and will cease to work with new versions of Firefox (starting with Firefox 47).  This breaks bok-choy's ability to run tests with Firefox.  To fix it, an update to bok-choy will be necessary (which may be a bit tricky since the actual use of FirefoxDriver is done through the needle package)

The fix for this is to use GeckoDriver/Marionette.  Unlike FirefoxDriver, this component is not bundled inside the selenium package.  It's more like Chrome/ChromeDriver, where you install a separate package to use the driver.  (note: GeckoDriver used to be called Wires, so you might not find much info yet if you search the interwebz for "GeckoDriver")

btw, Mozilla and the Selenium maintainers have done a really poor job of publicizing and easing this transition... so expect some pain 👊 

https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette
https://github.com/mozilla/geckodriver

**Comment by benpatterson** [comment]
@cgoldberg Thanks for keeping this front and center. Indeed your PSAs have been my only inbound source of info for these changes. 

We'll keep this queued up. I'll be curious if we get anything for free from Travis as well... Getting the driver for free in images with Firefox would simplify upgrades.

**Comment by dianakhuang** [comment]
I did some digging on this on OSX, and it looks like there a few issues with converting right now.

1. DevStack doesn't have a version of libc that will allow us to run the new geckodriver. 
2. The selenium driver is [only partially completed](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver/status).

**Comment by jzoldak** [comment]
Word on the street is that [Firefox 47.0.1](https://www.mozilla.org/en-US/firefox/47.0.1/releasenotes/) may have fixed the issue with the old driver. I haven't had a chance to investigate yet.

**Comment by cgoldberg** [comment]
>Firefox 47.0.1 may have fixed the issue

true.. but it breaks when you move to Firefox 48

**Comment by efischer19** [comment]
@jzoldak I was just bitten by this issue while running ORA acceptance tests on a fairly new devstack - I think the default version of firefox is now 49.0.2?

Test output:
```
======================================================================
ERROR: test_student_training (acceptance.tests.StudentTrainingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/edx/src/edx-ora2/test/acceptance/tests.py", line 473, in setUp
    super(StudentTrainingTest, self).setUp('student_training')
  File "/edx/src/edx-ora2/test/acceptance/tests.py", line 114, in setUp
    super(OpenAssessmentTest, self).setUp()
  File "/edx/src/edx-ora2/edx-ora2/local/lib/python2.7/site-packages/bok_choy/web_app_test.py", line 120, in setUp
    self.browser = browser(tags, self.proxy)
  File "/edx/src/edx-ora2/edx-ora2/local/lib/python2.7/site-packages/bok_choy/browser.py", line 203, in browser
    browser_check_func, "Browser is instantiated successfully.", timeout=30).fulfill()
  File "/edx/src/edx-ora2/edx-ora2/local/lib/python2.7/site-packages/bok_choy/promise.py", line 92, in fulfill
    is_fulfilled, result = self._check_fulfilled()
  File "/edx/src/edx-ora2/edx-ora2/local/lib/python2.7/site-packages/bok_choy/promise.py", line 118, in _check_fulfilled
    is_fulfilled, result = self._check_func()
  File "/edx/src/edx-ora2/edx-ora2/local/lib/python2.7/site-packages/bok_choy/browser.py", line 196, in browser_check_func
    return True, browser_class(*browser_args, **browser_kwargs)
  File "/edx/src/edx-ora2/edx-ora2/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 135, in __init__
    self.service.start()
  File "/edx/src/edx-ora2/edx-ora2/local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 
```

Some debugging info:
```
(edx-ora2) edxapp@precise64:/edx/src/edx-ora2$ apt-cache show firefox | grep Version
Version: 49.0.2+build2-0ubuntu0.12.04.1
Version: 11.0+build1-0ubuntu4
```

**Comment by cgoldberg** [comment]
> 'geckodriver' executable needs to be in PATH

geckodriver requires a new executable (like chromedriver does)

**Comment by cgoldberg** [comment]
closing old issues
