### ISSUE TITLE
Add Support for Query Chaining

### ISSUE THREAD

**Issue by clintonb** [edx/bok-choy#45]
After retrieving a parent element I would like to be able to make queries on the child elements. jQuery and Selenium offer real-world implementation examples.

``` html
<div class="parent">
  <div class="child"></div>
  <div class="child"></div>
</div>
```

``` python
page = ...

# Get the parent element
parent = page.q(css='div.parent')

# Get all of the children nested in the parent element
children = parent.q(css='div.child')

# Get the first child element
child = children[0]

# Infinite chaining (yes, the call below should fail since there is no span)
child.q(css='span')
```

**Comment by Kelketek** [comment]
@jzoldak Could a 'query specification' class be created somewhat like Django's Q? It might look something like:

    query = Q(css='div.special_class') && Q(css='div.additional_class')
    query.filter(css='div.child_class')
    # Actually sends the resulting query/filters/etc to selenium
    page.q(q=query)
